language: python
python:
    - "3.6.1"
# cache folders:
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/virtualenv/python3.6.1/lib/python3.6/site-packages
# sudo permission:
sudo: false
# Upgrade pip if possible
before_install:
  - pip install -U pip
# command to install dependencies
install:
    - pip install -r requirements.txt
# command to run tests
script:
    - py.test --cov=./
# command to run coverage
after_success:
    - coveralls
    - codecov
