language: python
python:
    - "3.7"
# cache folders:
cache:
  directories:
    - $HOME/.cache/pip
# sudo permission:
sudo: false
services:
  - postgresql
# Upgrade pip if possible
before_install:
  - pip install -U pip
  - psql -c 'CREATE DATABASE foodcravingsurvey;' -U postgres
# command to install dependencies
install:
    - pip install pipenv
    - pipenv install
# command to run tests
script:
    - py.test --cov=./
# command to run coverage
after_success:
    - coveralls
    - codecov
