language: python
python:
  - "3.6.1"
# command to install dependencies
install: "pip install -r requirements.txt"
# cache folders:
cache: pip
# sudo permission:
sudo: false
# command to run tests
script:
  - pytest --cov=backend/

# command to run coverage
after success:
  - codecov
  - coveralls
