"""ratings table

Revision ID: 889d4238323f
Revises: 3b4852cbf54c
Create Date: 2018-04-16 23:25:43.021170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '889d4238323f'
down_revision = '3b4852cbf54c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=16), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('participant_id', 'session_id', 'image')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    # ### end Alembic commands ###
